name: Prettier
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
      - name: Run Prettier
        run: make prettier
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier Change
